ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'QUOTED';
ALTER TYPE "ServiceRequestStatus" ADD VALUE IF NOT EXISTS 'QUOTE_DECLINED';

ALTER TABLE "ServiceRequest"
ADD COLUMN "quotedPrice" DOUBLE PRECISION,
ADD COLUMN "proposedAt" TIMESTAMP(3),
ADD COLUMN "quoteNote" TEXT;